### ISSUE TITLE
Scan/Get with a where clause

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/streamsx.hbase#32]
Is it possible to think about adding a whereclause parameter to limit the number of rows.

If we have a HBase table that contains status (0/1), I would like to scan or get data where status = 1.

**Comment by BruceGlassford** [comment]
I've got a customer use  case that needs this very badly.  Many millions of records - need to pull back  based on a value in a column value to get the subset I need.   RowID prefixes won't work since the data has random prefixes for distribution.     Pulling multiple terabytes of data over the network to Streams to filter them out will likely cause the network admins to be rather peeved with me, so the HbaseGet->Filter won't help.   Will take a look at the code and see if I can figure out how to add it rather than writing my own operator to do it.  Or if either of you has already got it in place, just needing testing PLEASE let me know...
