### ISSUE TITLE
Allow HBASEGet operator to accept stream attributes for params

### ISSUE THREAD

**Issue by nmwaara** [IBMStreams/streamsx.hbase#97]
This RFE was created based off a customer support case. The main goal is to allow the **tableName** param to be set to a stream attribute value (i.e. some non-hardcoded value) in order to allow a single HBASEGet operator to work on multiple HBase tables.

**Comment by anouri** [comment]
It is planned to discuss about delivery of a solution for this issue.
The first proposal is to add a new  dynamically parameter **tableNameAttribute** parallel to the exciting parameter **tableNme**.
Then it will be possible to set the name of table in two different ways:
**tableNme** for hardcoded value
Or the value of **tableNameAttribute** can be set over input streams.

**Comment by anouri** [comment]
It has to researched about the output streams.
If we use the table name as a dynamically parameter in input streams for HBSEGet, it will be work for table with the same schema.

**Comment by sharathsetty** [comment]
Thanks for looking into this RFE. It is going to help us use the toolkit and operator in our flows if we can pass in the table name dynamically through the stream instead of hardcoding it. Our flows have multiple sources of data coming in and based on data, we need to be able to route to different tables.

We don't want to create multiple instances of the flows to accommodate multiple tables. We would like our flows to be clean and dynamic and that would happen if this parameter can accept attribute that is passed in the stream so that they can be dynamic. We have similar flows working using apache storm and apache NiFi that accept the table name dynamically.

**Comment by anouri** [comment]
The HBASEGet feature with a new parameter "tableNameAttribute" is implemented in HBase toolkit v3.2.0.

https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.2.0

**Comment by sharathsetty** [comment]
@anouri , that is great! 
I was able to get the toolkit and verify that it worked.
Thanks you. Appreciate the enhancement.
Sharath

**Comment by nmwaara** [comment]
I believe this feature has been successfully added to the toolkit. I will close this now to remove it from the list of open issues for the HBase toolkit. If necessary, you can feel free to re-open this issue for future tracking purposes.
